version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  rails:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - '3000:3000'
    links:
      - db
    volumes:
      - ./:/home/app